version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: toss-up-postgres
    environment:
      POSTGRES_DB: toss_up
      POSTGRES_USER: toss_up
      POSTGRES_PASSWORD: toss_up_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
